export const COLORS = {
  primary: '#1A6B8A',
  primaryDark: '#145570',
  primaryLight: '#2A8BAA',
  secondary: '#E8F4F8',
  secondaryDark: '#C5E4ED',
  accent: '#F8D7DA',
  accentDark: '#F1AEB5',
  background: '#F5F9FB',
  surface: '#FFFFFF',
  textPrimary: '#1A2B3C',
  textSecondary: '#5A6B7C',
  textMuted: '#8A9BAC',
  border: '#E0E8ED',
  borderLight: '#F0F4F7',
  success: '#28A745',
  successLight: '#D4EDDA',
  warning: '#FFC107',
  warningLight: '#FFF3CD',
  danger: '#DC3545',
  dangerLight: '#F8D7DA',
  info: '#17A2B8',
  infoLight: '#D1ECF1',
  tabActive: '#1A6B8A',
  tabInactive: '#8A9BAC',
  chartBlue: '#1A6B8A',
  chartLightBlue: '#A8D8E8',
  chartPink: '#F1AEB5',
  calendarToday: '#1A6B8A',
  calendarDot: '#1A6B8A',
  calendarMuted: '#C5C5C5',
  badgeGreen: '#28A745',
  badgeBlue: '#1A6B8A',
  badgeRed: '#DC3545',
  badgeYellow: '#FFC107',
};

export const SHADOWS = {
  small: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  large: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
};
